defaults:
  - loss: mse.yaml
  - architecture: resnet.yaml

_target_: src.models.default_model_scheduler.DefaultModelScheduler
dir_preds_test: ${preds_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
lr: 0.001
use_scheduler: True
heatmap_size: ${heatmap_size} 