defaults:
  - loss: mse.yaml
  - architecture: resnet.yaml

_target_: src.models.regularized_model.RegularizedModel
dir_preds_test: ${preds_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
lr: 0.001
use_scheduler: False
heatmap_size: ${heatmap_size} 
heatmap_std: ${heatmap_std} 
regularization:
  _target_: src.models.losses.divergence_loss.DivergenceJS1D
  size: ${heatmap_size}
  use_softmax: False 