
wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${oc.env:WANDB_PROJECT}
  entity: ${oc.env:WANDB_ENTITY}
  # offline: False  # set True to store all logs only locally
  job_type: "train"
  group: ""
  save_dir: ${logs_dir}